<div class="usa-overlay"></div>
  <header class="usa-header usa-header--basic usa-header--megamenu">
    <div class="usa-nav-container">
      <div class="usa-navbar">
        <div class="usa-logo" id="basic-mega-logo">
          <em class="usa-logo__text"><a href="<?php echo $path;?>/" title="Home" aria-label="Home">Omid Ghaffari-Tabrizi</a></em>
        </div>
        <button class="usa-menu-btn">Menu</button>
      </div>
      <nav aria-label="Primary navigation" class="usa-nav">
        <div class="usa-nav__inner">
          <button class="usa-nav__close"><img src="<?php echo $path;?>assets/uswds/img/close.svg" alt="close"></button>
          <ul class="usa-nav__primary usa-accordion">
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="<?php echo $path;?>" alt="The home page and where I provide a little information about myself."><span>About Me</span></a></li>
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="<?php echo $path;?>liverpool-fc/" alt="A page that has a few quotes and things I like related to Liverpool FC."><span>Liverpool FC</span></a></li>
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="<?php echo $path;?>make-mom-proud/" alt="Media and other mentions of my work that made my mom proud of me."><span>Make Mom Proud</span></a></li>
            <li class="usa-nav__primary-item"><a href="<?php echo $path;?>make-dad-proud/" alt="Projects and ventures that would have made my dad proud of me."><span>Make Dad Proud</span></a></li>
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="https://www.letoupao.org/" alt="The official website of the LeTouPAO Foundation." target="_blank" rel="noopener noreferrer"><span>LeTouPAO Foundation</span></a></li>
          </ul>
        </div>
      </nav>
    </header>