<main id="main-content">
      <!-- Hero -->
      <section class="usa-hero" aria-label="Introduction">
        <div class="grid-container">
          <div class="usa-hero__callout">
            <h1 class="usa-hero__heading"><span class="usa-hero__heading--alt">Support charity:</span>
            </h1><p><a href="https://www.achanceinlife.org/" alt="A Chance In Life's website." target="_blank" rel="noopener noreferrer">A Chance In Life</a> has a <a href="https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=16343" alt="Charity Navigator's profile on A Chance In Life." target="_blank" rel="noopener noreferrer">perfect 100</a> on Charity Navigator.</p><a class="usa-button" href="https://www.achanceinlife.org/donate-now.html" alt="A Chance In Life's donation page." target="_blank" rel="noopener noreferrer">Become a supporter</a>
          </div>
        </div>
      </section>

      <!-- Biography -->
      <section class="grid-container usa-section">
        <div class="grid-row grid-gap">
          <div class="tablet:grid-col-4">
            <h2 class="font-heading-xl margin-top-0 tablet:margin-bottom-0">A little bit about me</h2>
          </div>
          <div class="tablet:grid-col-8 usa-prose">
            <p>My name is Omid Ghaffari-Tabrizi. I was born in Minnesota and raised in South Florida. I have lived in a few different places, but currently call D.C. my home. Despite how muggy the summers are, this city is incredible!</p>
            <p>I learned about the internet when two babysitters introduced me to <a href="https://en.wikipedia.org/wiki/Mosaic_(web_browser)" alt="The Wikipedia article on Mosaic, the web browser." target="_blank" rel="noopener noreferrer">Mosaic</a>. They were hired by an organization to update their website to reflect the winner of the NBA Finals as soon as the game was over.</p>
            <p>I couldn't believe I was sitting in the room where two young college students that had only recently come to the U.S., changed something on my computer in a matter of seconds (with a few minutes of uploading), and the entire world could see what they did.</p>
            <p>So I did what I could to be involved with technology.</p>
          </div>
        </div>
      </section>

      <!-- 4 highlights -->
      <section class="usa-graphic-list usa-section usa-section--dark">
        <div class="grid-container">
          <div class="usa-graphic-list__row grid-row grid-gap">
            <div class="usa-media-block tablet:grid-col">
              <img class="usa-media-block__img home-circle"  src="<?php echo $path;?>assets/images/graduated.png" alt="Icon of Lady Justice created by Eucalyp on Flaticon.com.">
              <div class="usa-media-block__body">
                <h2 class="usa-graphic-list__heading">I'm a licensed Florida attorney.</h2>
                <p>Depending on where I am working right now, I may not be able to represent you, but I keep my license active. I have represented people as well as companies.</p>
              </div>
            </div>
            <div class="usa-media-block tablet:grid-col">
              <img class="usa-media-block__img home-circle"  src="<?php echo $path;?>assets/images/team.png" alt="Icon of an Agile Team created by Eucalyp on Flaticon.com.">
              <div class="usa-media-block__body">
                <h2 class="usa-graphic-list__heading">I'm a certified Scrum Master.</h2>
                <p>Certifications don't equate to knowledge, but I like to think that my professional experiences, training, and mentors have gotten me to a point I have what it takes.</p>
              </div>
            </div>
          </div>
          <div class="usa-graphic-list__row grid-row grid-gap">
            <div class="usa-media-block tablet:grid-col">
              <img class="usa-media-block__img home-circle"  src="<?php echo $path;?>assets/images/monument.png" alt="Icon of a government building created by Eucalyp on Flaticon.com.">
              <div class="usa-media-block__body">
                <h2 class="usa-graphic-list__heading">I enjoy public service.</h2>
                <p>I started my legal career as an intern with the Miami-Dade Public Defender, represented teams working with various agencies, and worked for GSA at 18F, login.gov, and CoE.</p>
              </div>
            </div>
            <div class="usa-media-block tablet:grid-col">
              <img class="usa-media-block__img home-circle"  src="<?php echo $path;?>assets/images/technology.png" alt="Icon of a person using the latest technology created by Eucalyp on Flaticon.com.">
              <div class="usa-media-block__body">
                <h2 class="usa-graphic-list__heading">I automate everything I can.</h2>
                <p>I love learning new things. Helping teams eliminate manual and rote tasks allows the specialists to focus on what they're best at doing, bringing all of us up with them.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="test-section-id" class="usa-section">
        <div class="grid-container">
          <h2 class="font-heading-xl margin-y-0">Get in touch</h2>
          <p class="usa-intro">I'm always happy to connect. If you have some interesting ideas or just want to chat, get in touch and I'm sure we can find time to meet!</p>
          <a class="usa-button usa-button--big" href="https://www.linkedin.com/in/oghaffari/" alt="A link to my LinkedIn profile." target="_blank" rel="noopener noreferrer">Connect</a>
        </div>
      </section>
    </main>