<div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>" alt="The home page and where I provide a little information about myself.">About Me</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>liverpool-fc/" alt="A page that has a few quotes and things I like related to Liverpool FC.">Liverpool FC</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>make-mom-proud/" alt="Media and other mentions of my work that made my mom proud of me.">Make Mom Proud</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>make-dad-proud/" alt="Projects and ventures that would have made my dad proud of me.">Make Dad Proud</a></li>
              </ul>
            </nav>
          </div>
          
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Making My Dad Proud</h1>
            <p class="usa-intro">Experiments, Projects, and Ventures</p>
            <p>One of the greatest things that ever happened in my life was that after my dad's passing, one of his customers called me and told me that my dad had told him life was complete because of what my brothers and I had become. With my papers on Interoperability and Open Contracting, and everything else in my personal and professional life up until this point, I now feel the same.</p>
            <h3>Papers</h3>
            <p>
              <ul>
                <li><a href="<?php echo $path;?>interoperability">Interoperable Cloud, Global Leadership</a>: Advancing Artificial Intelligence and Emerging Technologies via Public Sector Procurement</li>
                <li><a href="<?php echo $path;?>open-contracting">Open Contracting in the U.S. Public Sector</a>: Converting Procurements from Documents to Data</li>
              </ul>
            </p>
            <h3>Projects</h3>
            <p>
              <ul>
                <li><a href="https://github.com/tourajghaffari/tigerfid" alt="" target="_blank" rel="noopener noreferrer">TigeRFID</a>, the open sourced creations of <a href="http://www.activewaveinc.com/" alt="" target="_blank" rel="noopener noreferrer">my father's company</a>.</li>
              </ul>
            </p>
          </main>
        </div>
      </div>
    </div>