<div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>" alt="The home page and where I provide a little information about myself.">About Me</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>liverpool-fc/" alt="A page that has a few quotes and things I like related to Liverpool FC.">Liverpool FC</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>make-mom-proud/" alt="Media and other mentions of my work that made my mom proud of me.">Make Mom Proud</a></li>
              </ul>
            </nav>
          </div>
          <!--
            <li><a href="URL" alt="" target="_blank" rel="noopener noreferrer">MONTH DD, 202Y - TEXT: Text</a></li>
          -->
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Making My Mom Proud</h1>
            <p class="usa-intro">Articles, Interviews, Talks, and Media Mentions</p>
            <p>These are the things I've done to make sure my Mom has something to brag about.</p>
            <h3>2021</h3>
            <h4>March</h4>
            <p>
              <ul>
                <li><a href="https://internetassociation.org/files/ia_ca-multi-association-letter-supporting-tmf-modernization_03-24-2021_cloud/" alt="" target="_blank" rel="noopener noreferrer">March 24, 2021 - Internet Association: Statement in support of modernizing the Technology Modernization Fund through the American Rescue Act</a></li>
                <li><a href="https://www.tvw.org/watch/?clientID=9375922947&eventID=2021031165" alt="" target="_blank" rel="noopener noreferrer">March 11, 2021 - Washington Senate Environment, Energy & Technology Committee: Public Hearing on E2SHB 1274, concerning cloud computing solutions (testimony and Q&A from 0:25:50 to 0:29:25)</a></li>
              </ul>
            </p>
            <h4>February</h4>
            <p>
              <ul>
                <li><a href="https://www.fcc.gov/ecfs/filing/10217105148980" alt="" target="_blank" rel="noopener noreferrer">February 16, 2021 - Federal Communications Commission: Comments of Internet Association Supporting the use of E-Rate Funds for Remote Learning During the Covid-19 Pandemic</a></li>
                <li><a href="https://documents.worldbank.org/en/publication/documents-reports/documentdetail/522181612428427520/disruptive-technologies-in-public-procurement" alt="" target="_blank" rel="noopener noreferrer">February 4, 2021 - The World Bank Group: Disruptive Technologies in Public Procurement</a></li>
                <li><a href="https://internetassociation.org/news/statement-on-internet-industry-letter-calling-for-additional-funds-for-the-technology-modernization-fund/" alt="" target="_blank" rel="noopener noreferrer">February 3, 2021 - Internet Association: Statement in support of President Biden's call for increasing funding to the Technology Modernization Fund</a></li>
              </ul>
            </p>
            <h4>January</h4>
            <p>
              <ul>
                <li><a href="https://www.tvw.org/watch/?eventID=2021011456" alt="" target="_blank" rel="noopener noreferrer">January 25, 2021 - Washington House State Government & Tribal Relations Committee: Public Hearing on HB 1274, concerning cloud computing solutions (testimony and Q&A from 1:18:20 to 1:24:25)</a></li>
                <li><a href="http://www.wcny.org/experts-warn-new-yorks-digital-infrastructure-needs-an-upgrade/" alt="" target="_blank" rel="noopener noreferrer">January 13, 2021 - Capitol Pressroom: Experts Warn New York's Digital Infrastructure Needs An Upgrade</a></li>
                <li><a href="https://www.crainsnewyork.com/op-ed/cloud-computing-can-help-new-york-shift-focus-infrastructure-services" alt="" target="_blank" rel="noopener noreferrer">January 8, 2021 - Crain's New York Business (behind paywall): Cloud computing can help New York shift focus from infrastructure to services</a></li>
              </ul>
            </p>
            <h3>2020</h3>
            <h4>Q4</h4>
            <p>
              <ul>
                <li><a href="https://mn.gov/governor/news/?id=1055-460928" alt="" target="_blank" rel="noopener noreferrer">December 21, 2020 - Minnesota Governor Tim Walz: Minnesota Leads Nation in Cybersecurity and IT Modernization Efforts</a></li>
                <li><a href="https://gcn.com/articles/2020/12/17/state-modernization-ratings.aspx" alt="" target="_blank" rel="noopener noreferrer">December 17, 2020 - GCN: Group rates states’ IT modernization work</a></li>
                <li><a href="https://fcw.com/blogs/fcw-insider/2020/12/dec16topstories.aspx" alt="" target="_blank" rel="noopener noreferrer">December 16, 2020 - FCW Insider: Quick Hits</a></li>
                <li><a href="https://www.spartnerships.com/pipeline/2020/government-contracting-pipeline-12-16-2020.html" alt="" target="_blank" rel="noopener noreferrer">December 16, 2020 - Government Contracting Pipeline: Minnesota, California, Florida rated most IT-ready states</a></li>
                <li><a href="https://www.bgov.com/core/news/#!/articles/QLFJFAT0AFB4" alt="" target="_blank" rel="noopener noreferrer">December 16, 2020 - BGov Tech and Cyber Briefing (behind paywall): Internet Association Releases Cyber Mapping</a></li>
                <li><a href="https://livestream.com/accounts/17376047/events/9081844/videos/214925642" alt="" target="_blank" rel="noopener noreferrer">December 15, 2020 - New York City Council Committee on Technology: Meeting on T2020-6906, Assessment of the feasibility of storing city agencies' electronic data on cloud computing systems (testimony and Q&A from 1:23:00 onwards)</a></li>
                <li><a href="https://www.route-fifty.com/tech-data/2020/12/these-states-are-best-prepared-challenges-cybersecurity-civic-tech/170753/" alt="" target="_blank" rel="noopener noreferrer">December 15, 2020 - Route-Fifty: These States Are Best Prepared for Challenges to Cybersecurity, Civic Tech</a></li>
                <li><a href="https://statescoop.com/internet-association-sitara-map/" alt="" target="_blank" rel="noopener noreferrer">December 15, 2020 - StateScoop: Tech lobby map rates states' cybersecurity and digital efforts</a></li>
                <li><a href="https://federalnewsnetwork.com/ask-the-cio-sled/2020/12/dc-trade-association-assesses-state-governments-cybersecurity-readiness/" alt="" target="_blank" rel="noopener noreferrer">December 15, 2020 - Federal News Network: DC trade association assesses state governments’ cybersecurity readiness</a></li>
                <li><a href="https://subscriber.politicopro.com/newsletter/2020/12/hack-campaign-puts-cisa-in-the-spotlight-792299">December 15, 2020 - POLITICO Pro Morning Cybersecurity (behind paywall): Skol, Cyber</a></li>
                <li><a href="https://subscriber.politicopro.com/newsletter/2020/12/hack-campaign-puts-cisa-in-the-spotlight-792299">December 15, 2020 - Internet Association: IA Launches The SITARA Map Assessing U.S. States’ And Territories’ Cybersecurity Posture And IT Modernization Efforts</a></li>
                <li><a href="https://insidecybersecurity.com/daily-news/industry-groups-weigh-cmmc-costs-guidelines-assessment-pentagon-interim-rule-takes-effect" alt="" target="_blank" rel="noopener noreferrer">December 4, 2020 - Inside Cybersecurity: Industry groups weigh in on CMMC costs, guidelines for assessment as Pentagon interim rule takes effect</a></li>
                <li><a href="https://beta.regulations.gov/document/DARS-2020-0034-0113" alt="" target="_blank" rel="noopener noreferrer">November 30, 2020 - Comments on the DFARS rule change implementing the Cybersecurity Maturity Model Certification (CMMC).</a></li>
                <li><a href="https://www.nextgov.com/cybersecurity/2020/11/government-reduces-representation-burdens-supply-chain-rule-banning-some-chinese-equipment/169721/" alt="" target="_blank" rel="noopener noreferrer">November 2, 2020 - Nextgov: Government Reduces Representation Burdens for Supply Chain Rule Banning Some Chinese Equipment</a></li>
                <li><a href="https://www.actiac.org/events/reimagine-nation-elc-2020" alt="" target="_blank" rel="noopener noreferrer">October 27, 2020 - ACT-IAC ReImagine Nation ELC 2020: The Road Forward – Intersection of Emerging Technology and Procurement</a></li>
                <li><a href="https://beta.regulations.gov/comment/FAR-2020-0051-0029" alt="" target="_blank" rel="noopener noreferrer">October 26, 2020 - Comments on Sequence No.2 of the FY2019 NDAA Section 889 Part B Rule Change</a></li>
                <li><a href="https://digital.gov/2020/10/26/discovery-bpa-evaluation-process-how-to-operationalize-this-practice/" alt="" target="_blank" rel="noopener noreferrer">October 26, 2020 - Digital.gov: Discovery BPA Evaluation Process: How to Operationalize this Practice</a></li>
              </ul>
            </p>
            <h4>Q3</h4>
            <p>
              <ul>
                <li><a href="https://beta.regulations.gov/comment/FAR-2019-0009-0042" alt="" target="_blank" rel="noopener noreferrer">September 14, 2020 - Comments on Sequence No.1 of FY2019 NDAA Section 889 Part B Rule Change</a></li>
                <li><a href="https://etc.g2xchange.com/statics/rising-gsa-centers-of-excellence-acquisitions-leader-exits/" alt="" target="_blank" rel="noopener noreferrer">July 29, 2020 - G2Exchange: Rising GSA Centers of Excellence Acquisitions Leader joins Internet Association</a></li>
                <li><a href="https://www.politico.com/newsletters/politico-influence/2020/07/16/what-the-chamber-wants-in-the-next-relief-bill-https://www.politico.com/newsletters/morning-tech/2020/07/17/what-does-the-twitter-attack-mean-for-november-789250" alt="" target="_blank" rel="noopener noreferrer">July 17, 2020 - POLITICO Morning Tech: What does the Twitter attack mean for November?</a></li>
                <li><a href="https://www.politico.com/newsletters/politico-influence/2020/07/16/what-the-chamber-wants-in-the-next-relief-bill-789227" alt="" target="_blank" rel="noopener noreferrer">July 16, 2020 - POLITICO Influence: What the Chamber wants in the next relief bill</a></li>
                <li><a href="https://internetassociation.org/news/internet-association-hires-new-cloud-policy-director/" alt="" target="_blank" rel="noopener noreferrer">July 16, 2020 - Internet Association Hires New Cloud Policy Director</a></li>
              </ul>
            </p>
            <h4>Q2</h4>
            <p>
              <ul>
                <li><a href="https://gcn.com/articles/2020/06/04/gsa-ai-bots.aspx" alt="" target="_blank" rel="noopener noreferrer">June 4, 2020 - GCN: GSA steps from automation to AI</a></li>
                <li><a href="https://fcw.com/articles/2020/06/03/rockwell-ai-acquisition-gsa.aspx" alt="" target="_blank" rel="noopener noreferrer">June 3, 2020 - FCW: Automation is advancing in federal acquisition</a></li>
                <li><a href="https://www.defenseone.com/feature/genius-machines-purchasing-with-the-power-of-artificial-intelligence/" alt="" target="_blank" rel="noopener noreferrer">June 3, 2020 - Defense One and Nextgov's Genius Machines: Purchasing with the Power of Artificial Intelligence</a></li>
                <li><a href="https://governmentciomedia.com/how-emerging-tech-can-improve-federal-acquisition-processes" alt="" target="_blank" rel="noopener noreferrer">May 21, 2020 - Government CIO Media: How Emerging Tech Can Improve Federal Acquisition Processes</a></li>
                <li><a href="https://www.actiac.org/events/emerging-technology-and-workforce-effecting-or-affected-question" alt="" target="_blank" rel="noopener noreferrer">May 20, 2020 - ACT-IAC Emerging Technology and the Workforce: Effecting or Affected? That is the Question</a></li>
                <li><a href="https://www.meritalk.com/articles/improving-the-federal-acquisition-process-through-modern-techniques/" alt="" target="_blank" rel="noopener noreferrer">May 19, 2020 - MeriTalk: Improving the Federal Acquisition Process Through Modern Techniques</a></li>
                <li><a href="https://www.actiac.org/events/act-iac-emerging-technology-coi-may-2020" alt="" target="_blank" rel="noopener noreferrer">May 19, 2020 - Emerging Technology Uses Cases in Acquisition</a></li>
                <li><a href="https://governmentciomedia.com/listen-gsa-centers-excellence-ai-leaders-omid-ghaffari-tabrizi-krista-kinnard" alt="" target="_blank" rel="noopener noreferrer">May 13, 2020 - GovernmentCIO GovCast Podcast: Season 3, Episode 15</a></li>
                <li><a href="https://digital.gov/2020/04/24/experimenting-with-micropurchase-threshold/" alt="" target="_blank" rel="noopener noreferrer">April 24, 2020 - Digital.gov: Experimenting with the Micro-Purchase Threshold</a></li>
              </ul>
            </p>
            <h4>Q1</h4>
            <p>
              <ul>
                <li><a href="https://digital.gov/event/2020/03/25/navigating-acquisition-procurement-for-artificial-intelligence/" alt="" target="_blank" rel="noopener noreferrer">March 25, 2020 - AI Community of Practice: Navigating Acquisition and Procurement for Artificial Intelligence and Advanced Data Analytics</a></li>
                <li><a href="https://18f.gsa.gov/2020/03/18/an-acquisition-retrospective/" alt="" target="_blank" rel="noopener noreferrer">March 18, 2020 - 18F Blog: An Acquisition Retrospective</a></li>
                <li><a href="https://nova.afceachapters.org/event/2nd-annual-intelligence-community-it-day" alt="" target="_blank" rel="noopener noreferrer">February 19, 2020 - AFCEA NOVA 2nd Annual Intelligence Community IT Day</a></li>
                <li><a href="https://www.linkedin.com/feed/update/urn:li:activity:6623302338050351104/" alt="" target="_blank" rel="noopener noreferrer">January 15, 2020 - DITAP training on Acqusition Innovation</a></li>
                <li><a href="https://www.rfid-smart.com/article/family-open-sources-entrepreneur-s-rfid-solutions.html" alt="" target="_blank" rel="noopener noreferrer">January 13, 2020 - RFID Smart: Family Open Sources Entrepreneur's RFID Solutions</a></li>
                <li><a href="https://governmentciomedia.com/gsa-explored-emerging-technologies-and-acquisition-innovation-2019" alt="" target="_blank" rel="noopener noreferrer">January 2, 2020 - Government CIO Media: GSA Explored Emerging Technologies and Acquisition Innovation in 2019 </a></li>
              </ul>
            </p>
            <h3>2019</h3>
            <p>
              <ul>
                <li><a href="https://www.federaltimes.com/it-networks/2019/12/06/how-the-pentagons-ai-team-can-benefit-civilian-agencies/" alt="" target="_blank" rel="noopener noreferrer">December 6, 2019 - Federal Times: How the Pentagon’s AI team can benefit civilian agencies</a></li>
                <li><a href="https://governmentciomedia.com/cxo-tech-forum-ai-2019" alt="" target="_blank" rel="noopener noreferrer">December 5, 2019 - GovernmentCIO CXO Tech Forum: AI and RPA in Government</a></li>
                <li><a href="https://fcw.com/articles/2019/10/31/rising-stars/rs_ghaffari.aspx" alt="" target="_blank" rel="noopener noreferrer">October 31, 2019 - FCW Government Innovation Rising Star Profile</a></li>
                <li><a href="https://fcw.com/articles/2019/08/26/rising-stars-2019.aspx" alt="" target="_blank" rel="noopener noreferrer">August 26, 2019 - FCW Government Innovation Rising Star Award</a></li>
                <li><a href="https://governmentciomedia.com/GSA-Centers-of-Excellence-Spur-Procurement-Innovation" alt="" target="_blank" rel="noopener noreferrer">June 25, 2019 - Government CIO Media: GSA's Centers of Excellence Spur Procurement Innovation</a></li>
                <li><a href="https://www.eventbrite.com/e/cxo-tech-forum-acquisition-innovation-tickets-54314881272?aff=efbneb#" alt="" target="_blank" rel="noopener noreferrer">June 20, 2019 - GovernmentCIO CXO Tech Forum: Acquisition Innovation</a></li>
                <li><a href="https://twitter.com/GSACoE/status/1141489654899888128" alt="" target="_blank" rel="noopener noreferrer">June 19, 2019 - NCMA DC Monthly Meeting</a></li>
                <li><a href="https://twitter.com/GSACoE/status/1126217478856687616" alt="" target="_blank" rel="noopener noreferrer">May 8, 2019 - Tweet explaining why I stayed at CoE</a></li>
                <li><a href="https://www.pscouncil.org/Shared_Content/Events/Event_Display?EventKey=1903TECH&WebsiteKey=502af8cb-491d-4e9b-b350-c7e3ff5bb9ee" alt="" target="_blank" rel="noopener noreferrer">March 5, 2019 - Professional Services Council: Discussion with the IT Modernization Centers of Excellence</a></li>
              </ul>
            </p>
            <h3>2018 and before</h3>
            <p>
              <ul>
                <li><a href="https://theoutline.com/post/4904/the-online-support-groups-for-former-inmates-and-their-loved-ones?zd=1&zi=hsb2waeg" alt="" target="_blank" rel="noopener noreferrer">June 10, 2018 - The Outline: The Online Groups for Former Inmates and Their Loved Ones</a></li>
                <li><a href="https://www.congress.gov/congressional-report/115th-congress/senate-report/209/" alt="" target="_blank" rel="noopener noreferrer">February 26, 2018 - Report of the Committe on Homeland Security and Governmental Affairs, United States Senate, to accompany S. 1281</a></li>
                <li><a href="https://digital.gov/2017/05/18/the-next-step-towards-a-bug-bounty-program-for-the-technology-transformation-service/" alt="" target="_blank" rel="noopener noreferrer">May 18, 2017 - Digital.gov: The Next Step Towards a Bug Bounty Program for the Technology Transformation Service</a></li>
                <li><a href="https://www.rfidjournal.com/family-open-sources-entrepreneurs-rfid-solutions" alt="" target="_blank" rel="noopener noreferrer">March 15, 2017 - RFID Journal: Family Open-Sources Entrepreneur’s RFID Solutions</a></li>
                <li><a href="https://www.gainesvilleregister.com/community/donations-help-support-state-school-football-program/article_21b86f00-5fd3-11e6-93bc-23dfbb0acb4f.html" alt="" target="_blank" rel="noopener noreferrer">August 11, 2016 -  The Gainesville Register: Donations help support state school football program </a></li>
                <li><a href="https://www.texasstandard.org/stories/this-football-team-has-a-booster-club-of-ex-convicts/" alt="" target="_blank" rel="noopener noreferrer">August 10, 2016 - The Texas Standard: This Football Team Has A Booster Club of Ex-Convicts</a></li>
                <li><a href="http://the8percent.com/football-is-breaking-down-the-cycle-of-youth-crime/" alt="" target="_blank" rel="noopener noreferrer">August 5, 2016 - The 8 Percent: Football is breaking down the cycle of youth crime</a></li>
                <li><a href="https://www.dallasobserver.com/arts/ex-convicts-are-raising-thousands-of-dollars-for-a-football-team-in-north-texas-8536934" alt="" target="_blank" rel="noopener noreferrer">July 28, 2016 - Dallas Observer: Ex-Convicts Are Raising Thousands of Dollars for a Football Team in North Texas</a></li>
                <li><a href="https://www.youtube.com/watch?v=ZoHFGnGtCrQ" alt="" target="_blank" rel="noopener noreferrer">December 9, 2008 - Boca Raton City Council special election speech</a></li>
              </ul>
            </p>
          </main>
        </div>
      </div>
    </div>