<div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>" alt="The home page and where I provide a little information about myself.">About Me</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>liverpool-fc/" alt="A page that has a few quotes and things I like related to Liverpool FC.">Liverpool FC</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>make-mom-proud/" alt="Media and other mentions of my work that made my mom proud of me.">Make Mom Proud</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>make-dad-proud/" alt="Projects and ventures that would have made my dad proud of me.">Make Dad Proud</a></li>
                <li class="usa-sidenav__item"><a href="https://www.letoupao.org/" alt="The official website of the LeTouPAO Foundation." target="_blank" rel="noopener noreferrer">LeTouPAO Foundation</a></li>
              </ul>
            </nav>
          </div>
          <!--
            <li><a href="URL" alt="" target="_blank" rel="noopener noreferrer">MONTH DD, 202Y - TEXT: Text</a></li>
          -->
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Making My Dad Proud</h1>
            <p class="usa-intro">Experiments, Projects, and Ventures</p>
            <p>These are the things I've built that I think would have made my Dad proud.</p>
            <h3>Continuing His Work</h3>
            <p>
              <ul>
                <li><a href="http://www.activewaveinc.com/" alt="" target="_blank" rel="noopener noreferrer">Active Wave, Inc.'s official website</a></li>
                <li><a href="https://github.com/tourajghaffari/tigerfid" alt="" target="_blank" rel="noopener noreferrer">TigeRFID's GitHub repo</a></li>
              </ul>
            </p>
          </main>
        </div>
      </div>
    </div>