<div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="/" alt="The home page and where I provide a little information about myself.">About Me</a></li>
                <li class="usa-sidenav__item"><a href="liverpool-fc.php" alt="A page that has a few quotes and things I like related to Liverpool FC.">Liverpool FC</a></li>
                <li class="usa-sidenav__item"><a href="make-mom-proud.php" alt="Media and other mentions of my work that made my mom proud of me.">Make Mom Proud</a></li>
              </ul>
            </nav>
          </div>
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Liverpool FC</h1>
            <p class="usa-intro">The Greatest Team to Ever Play the Game</p>
            <p>I am a huge Liverpool FC fan. This page has a few quotes that reflect why I love the team as much as I do. Never Give Up.</p>
            <p><img src="assets/images/lfc.jpg" alt="An amazing picture of Liverpool FC capitans holding up the Champions League trophy."></p>
            <h2 id="section-heading-h2">In the footsteps of giants</h2>
            <p>
              <blockquote>Liverpool was made for me and I was made for Liverpool.</blockquote><br/>
              <a href="https://en.wikipedia.org/wiki/Bill_Shankly" alt="The Wikipedia article on Bill Shankly, a great Liverpool manager." target="_blank" rel="noopener noreferrer">Bill Shankly</a>
            </p>
            <p>
              <blockquote>[Liverpool fans] were not concerned with cultured football but with triers who gave one hundred percent.</blockquote><br/>
              <a href="https://en.wikipedia.org/wiki/Bob_Paisley" alt="The Wikipedia article on Bob Paisley, a great Liverpool manager." target="_blank" rel="noopener noreferrer">Bob Paisley</a>
            </p>
            <h2 id="section-heading-h2">2005 - The Miracle of Istanbul</h2>
            <p>
              <blockquote>Don't let your heads drop. All the players who go onto the pitch after half-time have to keep their heads held high. We are Liverpool. You are playing for Liverpool, do not forget that. You have to hold your heads high for the supporters, you have to do it for them. You cannot call yourselves Liverpool players if you have your heads down. If we create a few chances, we have the possibility of getting back into this. Believe you can do it and we will. Give yourselves the chance to be heroes.</blockquote><br/>
              <a href="https://en.wikipedia.org/wiki/Rafael_Ben%C3%ADtez" alt="The Wikipedia article on Rafael Benitez, a great Liverpool manager." target="_blank" rel="noopener noreferrer">Rafael Benítez</a>, half-time speech, Champions League Final against AC Milan, 2005, Istanbul.</a>
            </p>
            <p><a href="https://vimeo.com/56773817" alt="A great highlight video of Liverpool's victory over AC Milan in the 2005 Champions League Final." target="_blank" rel="noopener noreferrer">Liverpool won on penalties</a> after being 3-0 down at half time in what was considered the greatest Champions League Final of all time.</p>
            <h2 id="section-heading-h2">2019 - The Improbable Comeback</h2>
            <p>
              <blockquote>I said to the boys before the game, "I don't think it's possible but because it's you we have a chance." Here's something everyone inside Anfield knows, including our opponents. This Liverpool never stops. This Liverpool never shut down. This Liverpool gives its all at all times.</blockquote><br/>
              <a href="https://en.wikipedia.org/wiki/J%C3%BCrgen_Klopp" alt="The Wikipedia article on Jurgen Klopp, a great Liverpool manager." target="_blank" rel="noopener noreferrer">Jürgen Klopp</a>, post-match interview, Champions League Semifinals against Barcelona, 2019, Liverpool.</a>
            </p>
            <p><a href="https://vimeo.com/334946533" alt="A great highlight video of Liverpool's victory over FC Barcelona in the 2019 Champions League Semifinal." target="_blank" rel="noopener noreferrer">Liverpool won on 4-3 aggregate</a> after being 3-0 down from the first leg in what was considered the greatest Champions League comeback of all time. <a href="https://streamable.com/ztyj0" alt="Part 1 of a great highlight video of Liverpool's run through the Champions League in 2019." target="_blank" rel="noopener noreferrer">Liverpool's run</a> culminated with <a href="https://streamable.com/tvfhu" alt="Part 2 of a great highlight video of Liverpool's run through the Champions League in 2019." target="_blank" rel="noopener noreferrer">a Final</a> against Tottenham.</p>
          </main>
        </div>
      </div>
    </div>