<div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>" alt="The home page and where I provide a little information about myself.">About Me</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>liverpool-fc/" alt="A page that has a few quotes and things I like related to Liverpool FC.">Liverpool FC</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>make-mom-proud/" alt="Media and other mentions of my work that made my mom proud of me.">Make Mom Proud</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>make-dad-proud/" alt="Projects and ventures that would have made my dad proud of me.">Make Dad Proud</a></li>
              </ul>
            </nav>
          </div>
          
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Making My Mom Proud</h1>
            <p class="usa-intro">Articles, Letters, Talks, and Media Mentions</p>
            <p>These are the things I've done to make sure my Mom has something to brag about.</p>
            <p>With the launch of a few personal and professional ventures, on June 2021, Mom told me I made her proud long ago. As a result, this page will be updated far less often.</p>
            <p>Here's to you, Mom.</p>
            <h3>2025</h3>
            <p>
              <ul>
                <li><a href="https://www.worldbank.org/en/events/2024/12/19/govtech-and-public-sector-innovation-global-forum" alt="" target="_blank" rel="noopener noreferrer">May 27, 2025 - The World Bank Group: GovTech and Public Sector Innovation Global Forum - Transforming Institutions in the Age of AI</a></li>
                <li><a href="https://events.govexec.com/the-2025-new-agenda/agenda/" alt="" target="_blank" rel="noopener noreferrer">May 1, 2025 - NextGov/FCW: The New Agenda</a></li>
                <li><a href="https://x.com/USGSA/status/1911132376375218465" alt="" target="_blank" rel="noopener noreferrer">April 12, 2025 - GSA: Post advertising the Google agreement</a></li>
                <li><a href="https://x.com/elonmusk/status/1910756386885034221" alt="" target="_blank" rel="noopener noreferrer">April 11, 2025 - Elon Musk: Post approving the GSA and Google agreement</a></li>
                <li><a href="https://x.com/DOGE/status/1910728527776809457" alt="" target="_blank" rel="noopener noreferrer">April 11, 2025 - DOGE: Post applauding the GSA and Google agreement</a></li>
                <li><a href="https://www.nextgov.com/acquisition/2025/04/googles-government-deal-first-many-come-doge-says/404508/" alt="" target="_blank" rel="noopener noreferrer">April 11, 2025 - NextGov/FCW: Google's government deal is the ‘first of many’ to come, DOGE says</a></li>
                <li><a href="https://www.benzinga.com/25/04/44765778/google-takes-on-microsoft-with-ai-powered-workspace-2-billion-savings-deal-for-us-agencies" alt="" target="_blank" rel="noopener noreferrer">April 11, 2025 - Benzinga: What's Going On With Google Parent Alphabet Stock On Friday?</a></li>
                <li><a href="https://executivegov.com/2025/04/gsa-google-deal-trim-workspace-cost/" alt="" target="_blank" rel="noopener noreferrer">April 11, 2025 - ExecutiveGov: GSA-Google Agreement to Cut Federal Agencies’ Google Workspace Fees</a></li>
                <li><a href="https://www.ccn.com/news/technology/google-offers-agencies-71-discount-switch-from-microsoft/" alt="" target="_blank" rel="noopener noreferrer">April 11, 2025 - CCN: Google Offers Agencies 71% Discount to Switch From Microsoft</a></li>
                <li><a href="https://www.computerworld.com/article/3960309/google-to-offer-its-workspace-suite-to-the-us-government-at-a-71-discount.html" alt="" target="_blank" rel="noopener noreferrer">April 11, 2025 - ComputerWorld: Google to offer its Workspace suite to the US government at a 71% discount</a></li>
                <li><a href="https://www.youtube.com/watch?v=Rke7JCbm5WA&t=3625s" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - President Trump: "I love Google" during questions from the press</a></li>
                <li><a href="https://arstechnica.com/gadgets/2025/04/google-slashes-workspace-pricing-for-feds-to-capitalize-on-cost-cutting/" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - Ars Technica:  Google takes advantage of federal cost-cutting with steep Workspace discount</a></li>
                <li><a href="https://www.reuters.com/technology/google-slashes-business-software-prices-us-federal-agencies-2025-04-10/" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - Reuters: Google slashes business software prices for US federal agencies</a></li>
                <li><a href="https://www.law360.com/articles/2323930/gsa-google-ink-deal-for-discount-on-workspace-pricing" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - Law360: GSA, Google Ink Deal For Discount On 'Workspace' Pricing</a></li>
                <li><a href="https://www.techradar.com/pro/google-workspace-is-offering-huge-discounts-for-the-us-government" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - TechRadar Pro: Google Workspace is offering huge discounts for the US government</a></li>
                <li><a href="https://fedscoop.com/gsa-google-announce-price-cut-for-agencies-on-workflow-tools-gemini/" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - FedScoop:  GSA, Google announce price cut for agencies on workflow tools, Gemini</a></li>
                <li><a href="https://www.meritalk.com/articles/gsa-google-reach-cost-saving-deal-for-google-workspace/" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - MeriTalk: GSA, Google Reach Cost-Saving Deal for Google Workspace</a></li>
                <li><a href="https://www.nextgov.com/acquisition/2025/04/google-gsa-agree-major-governmentwide-software-discount/404450/" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - NextGov/FCW: Google, GSA agree to major governmentwide software discount</a></li>
                <li><a href="https://cloud.google.com/blog/topics/public-sector/new-google-workspace-cost-saving-offer-available-for-us-federal-government" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - Google Cloud: New Google Workspace cost-saving offer available for U.S. federal government</a></li>
                <li><a href="https://www.gsa.gov/about-us/newsroom/news-releases/gsa-secures-cost-savings-through-strategic-agreement-with-google-04102025" alt="" target="_blank" rel="noopener noreferrer">April 10, 2025 - GSA: GSA secures cost savings through strategic agreement with Google</a></li>
                <li><a href="https://www.gao.gov/products/gao-25-106369" alt="" target="_blank" rel="noopener noreferrer">March 24, 2025 - GAO-25-106369 Cloud Computing: Private Sector Leading Practices in Acquisition, Cybersecurity, and Workforce Development</a></li>
                <li><a href="https://events.nextgov.com/future-of-the-caio/" alt="" target="_blank" rel="noopener noreferrer">March 19, 2025 - GovExec: AI in the New  Administration: The Future of the CAIO</a></li>
                <li><a href="https://www.lawfaremedia.org/about/masthead" alt="" target="_blank" rel="noopener noreferrer">March 10, 2025 - Lawfare: Masthead</a></li>
                <li><a href="https://www.lawfaremedia.org/article/unpacking-the-final-report-of-the-bipartisan-house-task-force-on-ai" alt="" target="_blank" rel="noopener noreferrer">February 19, 2025 - Lawfare:  Unpacking the Final Report of the Bipartisan House Task Force on AI</a></li>
              </ul>
            </p>
            <h3>2024</h3>
            <p>
              <ul>
                <li><a href="https://www.gsa.gov/about-us/newsroom/news-releases/gap-fac-welcomes-new-members-shifts-focus-to-emerging-tech-in-fed-procurement-12052024" alt="" target="_blank" rel="noopener noreferrer">December 5, 2024 - GSA: GSA Acquisition Policy Advisory Committee welcomes new members, shifts focus to emerging technology in federal procurement</a></li>
                <li><a href="https://www.lawfaremedia.org/article/memorandum-outlines-u.s.-government-s-role-in-ai-development" alt="" target="_blank" rel="noopener noreferrer">November 22, 2024 - Lawfare:  Memorandum Outlines U.S. Government’s Role in AI Development </a></li>
                <li><a href="https://www.lawfaremedia.org/contributors/oghaffaritabrizi" alt="" target="_blank" rel="noopener noreferrer">November 22, 2024 - Lawfare: Profile</a></li>
                <li>November 11, 2024 - DOE:  Notice of Request for Information (RFI) on Frontiers in AI for Science, Security, and Technology (FASST) Initiative (available upon request)</li>
                <li><a href="https://www.regulations.gov/comment/HHS-OS-2024-0015-0007" alt="" target="_blank" rel="noopener noreferrer">October 10, 2024 - HHS Acquisition Regulation: Information Technology; Standards for Health Information Technology</a></li>
                <li><a href="https://www.nist.gov/system/files/documents/2020/09/08/Comments-800-63-035.pdf" alt="" target="_blank" rel="noopener noreferrer">October 7, 2024 - NIST 800-63-4 Pre-Draft Call for Comments: Digital Identity Guidelines</a></li>
                <li><a href="https://www.whitehouse.gov/wp-content/uploads/2024/10/M-24-18-AI-Acquisition-Memorandum.pdf" alt="" target="_blank" rel="noopener noreferrer">September 24, 2024 - M-24-18: Advancing the Responsible Acquisition of Artificial Intelligence in Government</a></li>
                <li><a href="https://app.smartsheetgov.com/b/publish?EQBCT=be27aa7ed4404614a448e51112f28469" alt="" target="_blank" rel="noopener noreferrer">September 9, 2024 - Strengthening the Use of Cryptography to Secure Federal Cloud Systems</a></li>
                <li><a href="https://app.smartsheetgov.com/b/publish?EQBCT=2d86a23838f2450b97ee4d38424418e3" alt="" target="_blank" rel="noopener noreferrer">September 5, 2024 - FedRAMP Metrics for Public Comment</a></li>
                <li><a href="https://www.whitehouse.gov/wp-content/uploads/2024/07/M-24-15-Modernizing-the-Federal-Risk-and-Authorization-Management-Program.pdf" alt="" target="_blank" rel="noopener noreferrer">July 25, 2024 - M-24-15: Modernizing the Federal Risk and Authorization Management Program (FedRAMP)</a></li>
                <li><a href="https://www.gao.gov/products/gao-24-106946" alt="" target="_blank" rel="noopener noreferrer">June 20, 2024 - GAO-24-106946 Artificial Intelligence: Generative AI Technologies and Their Commercial Applications</a></li>
                <li><a href="https://www.regulations.gov/comment/OMB-2024-0004-0021" alt="" target="_blank" rel="noopener noreferrer">June 12, 2024 - OMB Request for Information on the Responsible Procurement of Artificial Intelligence in Government</a></li>
                <li>May 6, 2024 - Requestion for Information on AI in Health Care (available upon request)</li>
                <li><a href="https://app.smartsheetgov.com/b/publish?EQBCT=a6d4817ee88a49dd97d1c21e3d5aeafa" alt="" target="_blank" rel="noopener noreferrer">April 24, 2024 - Penetration Test Guidance Public Comment Period</a></li>
                <li><a href="https://www.actiac.org/documents/post-solicitation-best-practices" alt="" target="_blank" rel="noopener noreferrer">April 19, 2024 - ACT-IAC: Post-Solicitation Best Practices</a></li>
                <li><a href="https://www.whitehouse.gov/wp-content/uploads/2024/03/M-24-10-Advancing-Governance-Innovation-and-Risk-Management-for-Agency-Use-of-Artificial-Intelligence.pdf" alt="" target="_blank" rel="noopener noreferrer">March 28, 2024 - M-24-10: Advancing Governance, Innovation, and Risk Manangement for Agency Use of Artificial Intelligence</a></li>
                <li><a href="https://www.congress.gov/bill/118th-congress/senate-bill/4066" alt="" target="_blank" rel="noopener noreferrer">March 22, 2024 - S.4066: FIT Procurement Act</a></li>
                <li><a href="https://app.smartsheetgov.com/b/publish?EQBCT=50d962f467874f36842c68f478a3467d" alt="" target="_blank" rel="noopener noreferrer">March 11, 2024 - FedRAMP's Emerging Technology Prioritization Framework - Overview and Request for Comment</a></li>
                <li><a href="https://www.cta.tech/Resources/Newsroom/Media-Releases/2024/February/X" alt="" target="_blank" rel="noopener noreferrer">February 7, 2024 - ICYMI: CTA’s Gary Shapiro Joins Reps. Balderson and Kelly to Announce the Congressional Digital Health Caucus</a></li>
                <li><a href="https://www.gao.gov/products/gao-24-105717" alt="" target="_blank" rel="noopener noreferrer">January 29, 2024 - GAO-24-105717 Federal Software Licenses: Agencies Need to Take Action to Achieve Additional Savings</a></li>
              </ul>
            </p>
            <h3>2023</h3>
            <p>
              <ul>
                <li><a href="https://www.regulations.gov/comment/OMB-2023-0021-0135" alt="" target="_blank" rel="noopener noreferrer">December 22, 2023 - OMB Request for Comments on the Modernizing the Federal Risk Authorization Management Program (FedRAMP) Draft Memorandum</a></li>
                <li><a href="https://www.congress.gov/118/bills/hr2670/BILLS-118hr2670enr.pdf#page=445" alt="" target="_blank" rel="noopener noreferrer">December 22, 2023 - Section 1553 of the FY24 NDAA; Report on Department of Defense Enterprise Capabilties for Cybersecurity</a></li>
                <li><a href="https://sideaphotography.smugmug.com/Event-Galleries/Maryland-Chamber-of-Commerce/MDCC-Congressional-Roundup-2023/i-n4nVh4p" alt="" target="_blank" rel="noopener noreferrer">September 18, 2023 - Maryland Chamber of Commerce Congressional Roundup 2023 - AI: Transforming Business in the Digital Age</a></li>
                <li><a href="https://www.gao.gov/products/gao-23-106247" alt="" target="_blank" rel="noopener noreferrer">September 12, 2023 - GAO-23-106247 Cloud Computing: DOD Needs to Improve Tracking of Data User Fees</a></li>
                <li><a href="https://federalnewsnetwork.com/podcast/accelerating-government-show/accelerating-government-with-act-iac-episode-32-acquisition-cybersecurity/" alt="" target="_blank" rel="noopener noreferrer">September 6, 2023 - Accelerating Government with ACT-IAC - Episode 32: Acquisition & Cybersecurity</a></li>
                <li><a href="https://www.actiac.org/documents/pre-solicitation-best-practices" alt="" target="_blank" rel="noopener noreferrer">August 25, 2023 - ACT-IAC Pre-Solicitation Best Practices</a></li>
                <li><a href="https://www.gao.gov/products/gao-23-106222" alt="" target="_blank" rel="noopener noreferrer">July 27, 2023 - GAO-23-106222 Leading Practices: Iterative Cycles Enable Rapid Delivery of Complex, Innovative Products</a></li>
                <li><a href="https://www.youtube.com/watch?v=86U3qygg_0E&t=16s" alt="" target="_blank" rel="noopener noreferrer">July 23-26, 2023 - NCMA World Congress 2023</a></li>
                <li><a href="https://www.gao.gov/products/gao-23-105850" alt="" target="_blank" rel="noopener noreferrer">June 29, 2023 - GAO-23-105850 Artificial Intelligence: DOD Needs Department-Wide Guidance to Inform Acquisitions</a></li>
                <li><a href="https://www.gsa.gov/about-us/newsroom/news-releases/gsa-administrator-appoints-inaugural-members-to-th-05122023" alt="" target="_blank" rel="noopener noreferrer">May 12, 2023 - GSA Administrator appoints inaugural members to the Federal Secure Cloud Advisory Committee</a></li>
                <li><a href="https://www.flickr.com/photos/thecgp/52889298879/in/album-72177720308190711/" alt="" target="_blank" rel="noopener noreferrer">May 3, 2023 - Coalition for Government Procurement's Spring Training Conference</a></li>
                <li><a href="https://www.congress.gov/bill/118th-congress/senate-bill/931" alt="" target="_blank" rel="noopener noreferrer">March 22, 2023 - S.931: Strengthening Agency Management and Oversight of Software Assets Act</a></li>
                <li><a href="https://www.federalregister.gov/documents/2023/02/22/2023-03563/notice-of-high-performance-computing-hpc-summit" alt="" target="_blank" rel="noopener noreferrer">April 20, 2023 - Google HPC Presentation at the GSA High-Performance Computing (HPC) Summit</a></li>
                <li><a href="https://alliance4digitalinnovation.org/blog/2023/02/28/adi-cloud-security-event/" alt="" target="_blank" rel="noopener noreferrer">February 22, 2023 - Planned and hosted the ADI Cloud Security Event with CISA, OMB, ONCD, FedRAMP, and StateRAMP leadership</a></li>
              </ul>
            </p>
            <h3>2022</h3>
            <p>
              <ul>
                <li><a href="http://www.fosspatents.com/2022/10/clouded-in-secrecy-presumptively-amazon.html" alt="" target="_blank" rel="noopener noreferrer">October 17, 2022 - Clouded in secrecy: presumptively Amazon- and Google-backed U.S. lobbying front (Coalition for Fair Software Licensing) sets new opacity record by not listing any members</a></li>
                <li><a href="https://www.nist.gov/system/files/documents/2022/05/03/04-25-2022%20-%20OT%20Cyber%20Coalition_Redacted.pdf" alt="" target="_blank" rel="noopener noreferrer">April 25, 2022 - OT Cybersecurity Coalition's Response to NIST's RFI on Evaluating and Improving NIST Cybersecurity Resources</a></li>
                <li><a href="https://elibrary.ferc.gov/eLibrary/filelist?accession_num=20220328-5206" alt="" target="_blank" rel="noopener noreferrer">March 28, 2022 - OT Cybersecurity Coalition's Response to FERC's NPRM on Internal Network Security Monitoring for High and Medium Impact Bulk Electric System Cyber Systems</a></li>
                <li><a href="https://www.regulations.gov/comment/NIST-2021-0007-0063" alt="" target="_blank" rel="noopener noreferrer">February 16, 2022 - ECC's Response to NIST's RFI on the Study to Advance a More Productive Tech Economy</a></li>
              </ul>
            </p>
            <h3>2021</h3>
            <h4>December</h4>
            <p>
              <ul>
                <li><a href="https://www.nist.gov/system/files/documents/2022/01/18/ECC%20Response%20Draft%20Baseline%20Criteria%20for%20a%20Consumer%20Software%20Labeling%20Program.pdf" alt="" target="_blank" rel="noopener noreferrer">December 10, 2021 - ECC's Response to NIST's Draft Baseline Criteria for a Consumer Software Labeling Program</a></li>
                <li>December 10, 2021 - ECC's Response to Questions for Reviewers in Draft (2nd) NIST SP 800-161 Rev. 1: <a href="https://static1.squarespace.com/static/61b226c7c36d8e6f22a36e5d/t/61b378aa87af82078c175c8a/1639151786556/ECC+Comments+on+NIST+SP+800-161+Rev+1+Draft+2.pdf" alt="" target="_blank" rel="noopener noreferrer">Memo</a> and <a href="https://www.enterprisecloudcoalition.org/s/ECC-Comments-on-NIST-SP-800-161-Rev-1-Draft-2.xlsx" alt="" target="_blank" rel="noopener noreferrer">Excel Table</a></li>
              </ul>
            </p>
            <h4>November</h4>
            <p>
              <ul>
                <li><a href="https://www.regulations.gov/comment/GSA-GSA-2021-0021-0019" alt="" target="_blank" rel="noopener noreferrer">November 16, 2021 - ECC's Response to CDOC's Request for Information on their Mission and Focus</a></li>
                <li><a href="https://static1.squarespace.com/static/61b226c7c36d8e6f22a36e5d/t/61b2a0efc8ce75596bcf6117/1639096559864/ECC+Comments+on+NIST+SSDF+v1.1.pdf" alt="" target="_blank" rel="noopener noreferrer">November 4, 2021 - ECC's Response to NIST's Request for Comments on the Secure Software Development Framework (SSDF) v1.1</a></li>
              </ul>
            </p>
            <h4>July</h4>
            <p>
              <ul>
                <li><a href="https://www.politico.com/newsletters/morning-tech/2021/07/07/looking-ahead-to-the-next-jedi-showdown-796346" alt="" target="_blank" rel="noopener noreferrer">July 7, 2021 - Politico Morning Tech: Looking ahead to the next JEDI showdown</a></li>
                <li><a href="https://www.bgov.com/core/news/#!/articles/QLFJFAT0AFB4" alt="" target="_blank" rel="noopener noreferrer">July 7, 2021 - BGov Tech and Cyber Briefing (behind paywall): Monument Advocacy Hires Former Internet Association Exec</a></li>
                <li><a href="https://thehill.com/business-a-lobbying/lobbying-hires/561686-lobbying-world" alt="" target="_blank" rel="noopener noreferrer">July 7, 2021 - The Hill: Lobbying World</a></li>
                <li><a href="https://www.politico.com/newsletters/politico-influence/2021/07/06/exxon-hires-brownstein-796326" alt="" target="_blank" rel="noopener noreferrer">July 6, 2021 - Politico Influence: Exxon hires Brownstein, Monument beefs up its tech practice</a></li>
              </ul>
            </p>
            <h4>May</h4>
            <p>
              <ul>
                <li><a href="https://www.washingtonpost.com/politics/2021/05/27/technology-202-democrats-introduce-legislation-prohibiting-algorithmic-discrimination/" alt="" target="_blank" rel="noopener noreferrer">May 27, 2021 - Washington Post Technology 202: The U.S. Chamber of Commerce and other groups called for Biden to issue an executive order on federal use of facial recognition technology</a></li>
                <li><a href="https://americaninnovators.com/wp-content/uploads/2021/05/210524_Coalition_FacialRecognitionTech_POTUS.pdf" alt="" target="_blank" rel="noopener noreferrer">May 26, 2021 - Internet Association: Multi-trade letter supporting an executive order on facial recognition</a></li>
                <li><a href="https://www.meritalk.com/articles/tech-groups-pushing-for-750m-cisa-fy22-budget-bump/" alt="" target="_blank" rel="noopener noreferrer">May 21, 2021 - MeriTalk: Tech Groups Pushing for $750M CISA FY22 Budget Bump</a></li>
                <li><a href="https://potomacofficersclub.com/industry-groups-call-for-750m-budget-increase-for-cisa-in-fy2022/" alt="" target="_blank" rel="noopener noreferrer">May 21, 2021 - Potomac Officers Club: Industry Groups Call for $750M Budget Increase for CISA in FY2022</a></li>
                <li><a href="https://www.executivegov.com/2021/05/trade-groups-urge-congress-to-increase-fiscal-2022-cisa-budget-by-750m/" alt="" target="_blank" rel="noopener noreferrer">May 21, 2021 - ExecutiveGov: Trade Groups Urge Congress to Increase Fiscal 2022 CISA Budget by $750M</a></li>
                <li><a href="https://www.nextgov.com/cybersecurity/2021/05/industry-coalition-asks-appropriators-to-boost-cisa-funding/258825/" alt="" target="_blank" rel="noopener noreferrer">May 20, 2021 - NextGov/FCW: Industry coalition asks appropriators to boost CISA funding</a></li>
                <li><a href="https://insidecybersecurity.com/daily-news/industry-groups-ask-appropriators-increase-cisa-budget-cite-concerns-over-recent-attacks?s=na" alt="" target="_blank" rel="noopener noreferrer">May 20, 2021 - Inside Cybersecurity (behind paywall): Industry groups ask appropriators to increase CISA budget, cite concerns over recent attacks</a></li>
                <li><a href="https://www.washingtonpost.com/politics/2021/05/20/cybersecurity-202-industry-groups-express-cautious-optimism-about-biden-executive-order-software-standards/" alt="" target="_blank" rel="noopener noreferrer">May 20, 2021 - Washington Post Cybersecurity 202: Trade groups called for congressional appropriators to allocate $750 million more to CISA</a></li>
                <li><a href="<?php echo $path;?>assets/docs/2021-05-19-CISA-funding.pdf" alt="" target="_blank" rel="noopener noreferrer">May 19, 2021 - Internet Association: Multi-trade letter supporting increased funding for CISA</a></li>
                <li><a href="https://www.cramer.senate.gov/news/press-releases/sens-cramer-warner-lead-bipartisan-legislation-to-allow-remote-online-notarizations-nationwide" alt="" target="_blank" rel="noopener noreferrer">May 17, 2021 - Senator Kevin Cramer (R-ND): Sens. Cramer, Warner Lead Bipartisan Legislation to Allow Remote Online Notarizations Nationwide</a></li>
                <li>May 14, 2021 - Internet Association: Letter to New York State Senators supporting IT modernization efforts through S6515 (available upon request)</li>
                <li><a href="https://senatorkevincramer.app.box.com/s/tlvv3038gssvat34p6uthmw2zbrxgwl3" alt="" target="_blank" rel="noopener noreferrer">May 13, 2021 - Internet Association: Multi-organization letter supporting the SECURE Notarization Act</a></li>
                <li><a href="<?php echo $path;?>assets/docs/2021-05-05-WA-Cloud-Taskforce.pdf" alt="" target="_blank" rel="noopener noreferrer">May 5, 2021 - Washington Governor Jay Inslee: Appointment to the Washington State Cloud Transition Taskforce</a></li>
                <li><a href="https://www.legislature.ohio.gov/legislation/134/hb230/committee" alt="" target="_blank" rel="noopener noreferrer">May 5, 2021 - Ohio State House of Represenatives Technology and Innovation Committee: Written Testimony as a Proponent Supporting HB230</a></li>
                <li>May 3, 2021 - Internet Association: Letter to Texas State Representatives supporting cybersecurity efforts through SB475 (available upon request)</li>
              </ul>
            </p>
            <h4>April</h4>
            <p>
              <ul>
                <li><a href="https://internetassociation.org/files/ia_multi-association-letter-supporting-tmf-appropriations_04-30-2021_cloud-pdf/" alt="" target="_blank" rel="noopener noreferrer">April 30, 2021 - Internet Association: Multi-trade letter supporting President Biden's request for additional funding for the Technology Modernization Fund</a></li>
                <li><a href="https://internetassociation.org/files/ia_letter-supporting-fedramp-modernization-with-recommendations_04-30-2021_cloud/" alt="" target="_blank" rel="noopener noreferrer">April 30, 2021 - Internet Association: Letter to General Services Administration leadership with recommendations on FedRAMP modernization</a></li>
                <li><a href="https://morningconsult.com/opinions/nist-needs-help-to-improve-face-recognition-vendor-tests/" alt="" target="_blank" rel="noopener noreferrer">April 21, 2021 - Morning Consult: NIST Needs Help To Improve Face Recognition Vendor Tests</a></li>
                <li><a href="https://insidecybersecurity.com/daily-news/groups-weigh-proposed-incident-reporting-requirement-financial-sector-issue-draws" alt="" target="_blank" rel="noopener noreferrer">April 16, 2021 - Inside Cybersecurity (behind paywall): Groups weigh in on proposed incident-reporting requirement in financial sector, as issue draws interest in Congress</a></li>
                <li><a href="https://web.archive.org/web/20210505223750/https://www.youtube.com/watch?v=i1R5SQXy15c" alt="" target="_blank" rel="noopener noreferrer">April 16, 2021 - Internet Association: A Look At Policy Challenges For Cloud Security In The Public Sector for Congressional staffers</a></li>
                <li><a href="https://www.tvw.org/watch/?clientID=9375922947&eventID=2021041216">April 14, 2021 - Washington Governor Jay Inslee: Bill signing of HB 1274 concerning cloud computing (signing from 10:45 to 11:20)</a></li>
                <li><a href="https://internetassociation.org/news/tech-and-business-groups-urge-investment-in-it-modernization-of-face-recognition-vendor-tests/">April 14, 2021 - Internet Association: Tech And Business Groups Urge Investment In IT Modernization Of Face Recognition Vendor Tests</a></li>
                <li><a href="https://internetassociation.org/files/ia_multi-trade-letter-supporting-nist-frvt-it-infra-upgrade_04-14-2021_cloud/" alt="" target="_blank" rel="noopener noreferrer">April 14, 2021 - Internet Association: Multi-association letter supporting the IT infrastructure of NIST's FRVT labs</a></li>
                <li><a href="https://www.regulations.gov/comment/OCC-2020-0038-0012" alt="" target="_blank" rel="noopener noreferrer">April 12, 2021 - Financial Agencies (OCC, FDIC, Federal Reserve): Comments on the Proposed Rule Related to Computer-Security Incident Notification Requirements for Banking Organizations and Their Bank Service Providers</a></li>
                <li>April 7, 2021 - Internet Association: Letter to Washington Governor Jay Inslee encouraging him to sign HB1274 into law (available upon request)</li>
                <li><a href="https://www.fcc.gov/ecfs/filing/10405085842211" alt="" target="_blank" rel="noopener noreferrer">April 5, 2021 - Federal Communications Commission: Comments of Internet Association Supporting the use of the Emergency Connectivity Fund for additional cloud-based educational resources</a></li>
                <li>April 2, 2021 - Internet Association: Letter to California State Assemblymembers supporting IT modernization efforts through AB1323 (available upon request)</li>
                <li>April 1, 2021 - Internet Association: Letter to Texas State Senators seeking clarification on cybersecurity efforts through SB475 (available upon request)</li>
              </ul>
            </p>
            <h4>March</h4>
            <p>
              <ul>
                <li>March 26, 2021 - Internet Association: Letter to Florida State Senators supporting digital transformation efforts through SB1640 (available upon request)</li>
                <li>March 26, 2021 - Internet Association: Letter to Florida State Representatives supporting digital transformation efforts through HB1291 (available upon request)</li>
                <li>March 26, 2021 - Internet Association: Letter to Florida State Representatives supporting digital transformation efforts through HB1137 (available upon request)</li>
                <li>March 26, 2021 - Internet Association: Letter to Minnesota State Senators supporting digital transformation efforts through SF416 (available upon request)</li>
                <li>March 26, 2021 - Internet Association: Letter to Minnesota State Representatives supporting digital transformation efforts through HF35 (available upon request)</li>
                <li><a href="https://internetassociation.org/files/ia_ca-multi-association-letter-supporting-tmf-modernization_03-24-2021_cloud/" alt="" target="_blank" rel="noopener noreferrer">March 24, 2021 - Internet Association: Letter to Congressional leadership in support of modernizing the Technology Modernization Fund through the American Rescue Act</a></li>
                <li><a href="<?php echo $path;?>assets/docs/2021-03-24-NIST-Physical-Infra.pdf" alt="" target="_blank" rel="noopener noreferrer">March 24, 2021 - Internet Association: Letter to Congressional appropriators supporting additional funding for the physical infrastructure of the National Institute of Standards and Technology</a></li>
                <li>March 24, 2021 - Internet Association: Letter to Texas State Senators supporting IT modernization efforts through SB1197 (available upon request)</li>
                <li><a href="https://www.tvw.org/watch/?clientID=9375922947&eventID=2021031165" alt="" target="_blank" rel="noopener noreferrer">March 11, 2021 - Washington Senate Environment, Energy & Technology Committee: Public Hearing on E2SHB 1274, concerning cloud computing solutions (testimony and Q&A from 0:25:50 to 0:29:25)</a></li>
                <li>March 5, 2021 - Internet Association: Letter to Minnesota State Senators opposing government-mandated spyware through SF737 (available upon request)</li>
                <li>March 3, 2021 - Internet Association: Letter to West Virginia State Representatives supporting IT modernization efforts through HB2786 (available upon request)</li>
              </ul>
            </p>
            <h4>February</h4>
            <p>
              <ul>
                <li><a href="https://www.fcc.gov/ecfs/filing/10217105148980" alt="" target="_blank" rel="noopener noreferrer">February 16, 2021 - Federal Communications Commission: Comments of Internet Association Supporting the use of E-Rate Funds for Remote Learning During the Covid-19 Pandemic</a></li>
                <li>February 8, 2021 - Internet Association: Letter to Georgia State Senators supporting IT mdoernization efforts through SB53 (available upon request)</li>
                <li><a href="https://documents.worldbank.org/en/publication/documents-reports/documentdetail/522181612428427520/disruptive-technologies-in-public-procurement" alt="" target="_blank" rel="noopener noreferrer">February 4, 2021 - The World Bank Group: Disruptive Technologies in Public Procurement</a></li>
                <li><a href="https://internetassociation.org/news/statement-on-internet-industry-letter-calling-for-additional-funds-for-the-technology-modernization-fund/" alt="" target="_blank" rel="noopener noreferrer">February 3, 2021 - Internet Association: Statement in support of President Biden's call for increasing funding to the Technology Modernization Fund</a></li>
              </ul>
            </p>
            <h4>January</h4>
            <p>
              <ul>
                <li>January 29, 2021 - Cybersecurity & Infrastructure Agency - Feedback related to the Trusted Internet Connection (TIC) 3.0 Volume 2 Documentation (available upon request)</li>
                <li>January 29, 2021 - Internet Association: Letter to Washington State Representatives supporting IT modernization efforts through HB1274 (available upon request)</li>
                <li><a href="<?php echo $path;?>assets/docs/2021-01-27-World-Bank.pdf" alt="" target="_blank" rel="noopener noreferrer">January 27, 2021 - The World Bank Group: Speech related to the use of disruptive technologies in the procurement space</a></li>
                <li>January 26, 2021 - Internet Association: Letter to Iowa State Representatives supporting IT modernization efforts through HSB111 (available upon request)</li>
                <li><a href="https://www.tvw.org/watch/?eventID=2021011456" alt="" target="_blank" rel="noopener noreferrer">January 25, 2021 - Washington House State Government & Tribal Relations Committee: Public Hearing on HB 1274, concerning cloud computing solutions (testimony and Q&A from 1:18:20 to 1:24:25)</a></li>
                <li><a href="https://capitolpressroom.org/2021/01/13/experts-warn-new-yorks-digital-infrastructure-needs-an-upgrade/" alt="" target="_blank" rel="noopener noreferrer">January 13, 2021 - Capitol Pressroom: Experts Warn New York's Digital Infrastructure Needs An Upgrade</a></li>
                <li><a href="https://www.crainsnewyork.com/op-ed/cloud-computing-can-help-new-york-shift-focus-infrastructure-services" alt="" target="_blank" rel="noopener noreferrer">January 8, 2021 - Crain's New York Business (behind paywall): Cloud computing can help New York shift focus from infrastructure to services</a></li>
              </ul>
            </p>
            <h3>2020</h3>
            <h4>Q4</h4>
            <p>
              <ul>
                <li><a href="https://mn.gov/governor/newsroom/press-releases/#/detail/appId/1/id/460928" alt="" target="_blank" rel="noopener noreferrer">December 21, 2020 - Minnesota Governor Tim Walz: Minnesota Leads Nation in Cybersecurity and IT Modernization Efforts</a></li>
                <li><a href="https://www.route-fifty.com/infrastructure/2020/12/group-rates-states-it-modernization-work/315733/" alt="" target="_blank" rel="noopener noreferrer">December 17, 2020 - Route Fifty: Group rates states’ IT modernization work</a></li>
                <li><a href="https://www.nextgov.com/digital-government/2020/12/fcw-insider-dec-16/249861/" alt="" target="_blank" rel="noopener noreferrer">December 16, 2020 - NextGov/FCW: Insider Quick Hits</a></li>
                <li><a href="https://www.spartnerships.com/pipeline/2020/government-contracting-pipeline-12-16-2020.html" alt="" target="_blank" rel="noopener noreferrer">December 16, 2020 - Government Contracting Pipeline: Minnesota, California, Florida rated most IT-ready states</a></li>
                <li><a href="https://www.bgov.com/core/news/#!/articles/QLFJFAT0AFB4" alt="" target="_blank" rel="noopener noreferrer">December 16, 2020 - BGov Tech and Cyber Briefing (behind paywall): Internet Association Releases Cyber Mapping</a></li>
                <li>December 16, 2020 - Internet Association: Letter to New Jersey State Assemblymembers opposing government-mandated spyware through S1965 (available upon request)</li>
                <li><a href="https://livestream.com/accounts/17376047/events/9081844/videos/214925642" alt="" target="_blank" rel="noopener noreferrer">December 15, 2020 - New York City Council Committee on Technology: Meeting on T2020-6906, Assessment of the feasibility of storing city agencies' electronic data on cloud computing systems (testimony and Q&A from 1:23:00 onwards)</a></li>
                <li><a href="https://www.route-fifty.com/tech-data/2020/12/these-states-are-best-prepared-challenges-cybersecurity-civic-tech/170753/" alt="" target="_blank" rel="noopener noreferrer">December 15, 2020 - Route-Fifty: These States Are Best Prepared for Challenges to Cybersecurity, Civic Tech</a></li>
                <li><a href="https://statescoop.com/internet-association-sitara-map/" alt="" target="_blank" rel="noopener noreferrer">December 15, 2020 - StateScoop: Tech lobby map rates states' cybersecurity and digital efforts</a></li>
                <li><a href="https://federalnewsnetwork.com/ask-the-cio-sled/2020/12/dc-trade-association-assesses-state-governments-cybersecurity-readiness/" alt="" target="_blank" rel="noopener noreferrer">December 15, 2020 - Federal News Network: DC trade association assesses state governments’ cybersecurity readiness</a></li>
                <li><a href="https://subscriber.politicopro.com/newsletter/2020/12/hack-campaign-puts-cisa-in-the-spotlight-792299">December 15, 2020 - POLITICO Pro Morning Cybersecurity (behind paywall): Skol, Cyber</a></li>
                <li><a href="https://subscriber.politicopro.com/newsletter/2020/12/hack-campaign-puts-cisa-in-the-spotlight-792299">December 15, 2020 - Internet Association: IA Launches The SITARA Map Assessing U.S. States’ And Territories’ Cybersecurity Posture And IT Modernization Efforts</a></li>
                <li><a href="https://insidecybersecurity.com/daily-news/industry-groups-weigh-cmmc-costs-guidelines-assessment-pentagon-interim-rule-takes-effect" alt="" target="_blank" rel="noopener noreferrer">December 4, 2020 - Inside Cybersecurity (behind paywall): Industry groups weigh in on CMMC costs, guidelines for assessment as Pentagon interim rule takes effect</a></li>
                <li><a href="https://www.regulations.gov/comment/DARS-2020-0034-0113" alt="" target="_blank" rel="noopener noreferrer">November 30, 2020 - Internet Association: Comments on the DFARS rule change implementing the Cybersecurity Maturity Model Certification (CMMC).</a></li>
                <li><a href="https://www.nextgov.com/cybersecurity/2020/11/government-reduces-representation-burdens-supply-chain-rule-banning-some-chinese-equipment/169721/" alt="" target="_blank" rel="noopener noreferrer">November 2, 2020 - NextGov/FCW: Government Reduces Representation Burdens for Supply Chain Rule Banning Some Chinese Equipment</a></li>
                <li><a href="https://www.actiac.org/events/reimagine-nation-elc-2020" alt="" target="_blank" rel="noopener noreferrer">October 27, 2020 - ACT-IAC ReImagine Nation ELC 2020: The Road Forward – Intersection of Emerging Technology and Procurement</a></li>
                <li><a href="https://www.regulations.gov/comment/FAR-2020-0051-0029" alt="" target="_blank" rel="noopener noreferrer">October 26, 2020 - Comments on Sequence No.2 of the FY2019 NDAA Section 889 Part B Rule Change</a></li>
                <li>October 20, 2020 - Internet Association: Letter to New Jersey State Assembly supporting IT Modernization through A2614 (available upon request)</li>
                <li><a href="https://digital.gov/2020/10/26/discovery-bpa-evaluation-process-how-to-operationalize-this-practice/" alt="" target="_blank" rel="noopener noreferrer">October 26, 2020 - Digital.gov: Discovery BPA Evaluation Process: How to Operationalize this Practice</a></li>
              </ul>
            </p>
            <h4>Q3</h4>
            <p>
              <ul>
                <li><a href="https://www.regulations.gov/comment/FAR-2019-0009-0042" alt="" target="_blank" rel="noopener noreferrer">September 14, 2020 - Internet Association: Comments on Sequence No.1 of FY2019 NDAA Section 889 Part B Rule Change</a></li>
                <li><a href="https://app.g2xchange.com/fedciv/posts/rising-gsa-centers-of-excellence-acquisitions-leader-exits" alt="" target="_blank" rel="noopener noreferrer">July 29, 2020 - G2Exchange: Rising GSA Centers of Excellence Acquisitions Leader joins Internet Association</a></li>
                <li><a href="https://www.politico.com/newsletters/morning-tech/2020/07/17/what-does-the-twitter-attack-mean-for-november-789250" alt="" target="_blank" rel="noopener noreferrer">July 17, 2020 - POLITICO Morning Tech: What does the Twitter attack mean for November?</a></li>
                <li><a href="https://www.politico.com/newsletters/politico-influence/2020/07/16/what-the-chamber-wants-in-the-next-relief-bill-789227" alt="" target="_blank" rel="noopener noreferrer">July 16, 2020 - POLITICO Influence: What the Chamber wants in the next relief bill</a></li>
                <li><a href="https://internetassociation.org/news/internet-association-hires-new-cloud-policy-director/" alt="" target="_blank" rel="noopener noreferrer">July 16, 2020 - Internet Association: IA Hires New Cloud Policy Director</a></li>
              </ul>
            </p>
            <h4>Q2</h4>
            <p>
              <ul>
                <li><a href="https://www.route-fifty.com/digital-government/2020/06/gsa-steps-from-automation-to-ai/315178/" alt="" target="_blank" rel="noopener noreferrer">June 4, 2020 - Route Fifty: GSA steps from automation to AI</a></li>
                <li><a href="https://www.nextgov.com/modernization/2020/06/automation-is-advancing-in-federal-acquisition/257965/" alt="" target="_blank" rel="noopener noreferrer">June 3, 2020 - NextGov/FCW: Automation is advancing in federal acquisition</a></li>
                <li><a href="https://www.defenseone.com/feature/genius-machines-purchasing-with-the-power-of-artificial-intelligence/" alt="" target="_blank" rel="noopener noreferrer">June 3, 2020 - Defense One and Nextgov's Genius Machines: Purchasing with the Power of Artificial Intelligence</a></li>
                <li><a href="https://governmentciomedia.com/how-emerging-tech-can-improve-federal-acquisition-processes" alt="" target="_blank" rel="noopener noreferrer">May 21, 2020 - Government CIO Media: How Emerging Tech Can Improve Federal Acquisition Processes</a></li>
                <li><a href="https://www.actiac.org/events/emerging-technology-and-workforce-effecting-or-affected-question" alt="" target="_blank" rel="noopener noreferrer">May 20, 2020 - ACT-IAC: Emerging Technology and the Workforce</a></li>
                <li><a href="https://www.meritalk.com/articles/improving-the-federal-acquisition-process-through-modern-techniques/" alt="" target="_blank" rel="noopener noreferrer">May 19, 2020 - MeriTalk: Improving the Federal Acquisition Process Through Modern Techniques</a></li>
                <li><a href="https://www.actiac.org/events/act-iac-emerging-technology-coi-may-2020" alt="" target="_blank" rel="noopener noreferrer">May 19, 2020 - ACT-IAC: Emerging Technology Uses Cases in Acquisition</a></li>
                <li><a href="https://governmentciomedia.com/listen-gsa-centers-excellence-ai-leaders-omid-ghaffari-tabrizi-krista-kinnard" alt="" target="_blank" rel="noopener noreferrer">May 13, 2020 - GovernmentCIO GovCast Podcast: Season 3, Episode 15</a></li>
                <li><a href="https://digital.gov/2020/04/24/experimenting-with-micropurchase-threshold/" alt="" target="_blank" rel="noopener noreferrer">April 24, 2020 - Digital.gov: Experimenting with the Micro-Purchase Threshold</a></li>
              </ul>
            </p>
            <h4>Q1</h4>
            <p>
              <ul>
                <li><a href="https://digital.gov/event/2020/03/25/navigating-acquisition-procurement-for-artificial-intelligence/" alt="" target="_blank" rel="noopener noreferrer">March 25, 2020 - AI Community of Practice: Navigating Acquisition and Procurement for Artificial Intelligence and Advanced Data Analytics</a></li>
                <li><a href="https://web.archive.org/web/20250124013602/https://18f.gsa.gov/2020/03/18/an-acquisition-retrospective/" alt="" target="_blank" rel="noopener noreferrer">March 18, 2020 - 18F: An Acquisition Retrospective</a></li>
                <li><a href="https://nova.afceachapters.org/speaker/mr-omid-ghaffari-tabrizi" alt="" target="_blank" rel="noopener noreferrer">February 19, 2020 - AFCEA NOVA: 2nd Annual Intelligence Community IT Day</a></li>
                <!-- https://nova.afceachapters.org/event/2nd-annual-intelligence-community-it-day no longer works; archive is broken -->
                <li><a href="https://www.linkedin.com/feed/update/urn:li:activity:6623302338050351104/" alt="" target="_blank" rel="noopener noreferrer">January 15, 2020 - DITAP: Training Seminar on Acqusition Innovation</a></li>
                <li><a href="https://governmentciomedia.com/gsa-explored-emerging-technologies-and-acquisition-innovation-2019" alt="" target="_blank" rel="noopener noreferrer">January 2, 2020 - Government CIO Media: GSA Explored Emerging Technologies and Acquisition Innovation in 2019 </a></li>
              </ul>
            </p>
            <h3>2019</h3>
            <p>
              <ul>
                <li><a href="https://www.federaltimes.com/it-networks/2019/12/06/how-the-pentagons-ai-team-can-benefit-civilian-agencies/" alt="" target="_blank" rel="noopener noreferrer">December 6, 2019 - Federal Times: How the Pentagon’s AI team can benefit civilian agencies</a></li>
                <li><a href="https://govciomedia.com/events/archive/cxo-tech-forum-a-government-2019-recap/" alt="" target="_blank" rel="noopener noreferrer">December 5, 2019 - GovernmentCIO CXO Tech Forum: AI and RPA in Government</a></li>
                <li><a href="https://www.nextgov.com/acquisition/2019/10/rising-star-omid-ghaffari-tabrizi/256252/" alt="" target="_blank" rel="noopener noreferrer">October 31, 2019 - NextGov/FCW: Government Innovation Rising Star Profile</a></li>
                <li><a href="https://www.nextgov.com/acquisition/2019/08/congratulations-to-the-2019-rising-stars/210967/" alt="" target="_blank" rel="noopener noreferrer">August 26, 2019 - NextGov/FCW: Government Innovation Rising Star Award</a></li>
                <li><a href="https://governmentciomedia.com/GSA-Centers-of-Excellence-Spur-Procurement-Innovation" alt="" target="_blank" rel="noopener noreferrer">June 25, 2019 - Government CIO Media: GSA's Centers of Excellence Spur Procurement Innovation</a></li>
                <li><a href="https://www.eventbrite.com/e/cxo-tech-forum-acquisition-innovation-tickets-54314881272?aff=efbneb#" alt="" target="_blank" rel="noopener noreferrer">June 20, 2019 - GovernmentCIO CXO Tech Forum: Acquisition Innovation</a></li>
                <li><a href="https://twitter.com/GSACoE/status/1141489654899888128" alt="" target="_blank" rel="noopener noreferrer">June 19, 2019 - National Contract Management Association: Invited Speaker at the DC Monthly Meeting</a></li>
                <li><a href="https://twitter.com/GSACoE/status/1126217478856687616" alt="" target="_blank" rel="noopener noreferrer">May 8, 2019 - Centers of Excellence - Tweet explaining why I stayed at CoE</a></li>
                <li><a href="https://www.pscouncil.org/Shared_Content/Events/Event_Display?EventKey=1903TECH&WebsiteKey=502af8cb-491d-4e9b-b350-c7e3ff5bb9ee" alt="" target="_blank" rel="noopener noreferrer">March 5, 2019 - Professional Services Council: Discussion with the IT Modernization Centers of Excellence</a></li>
              </ul>
            </p>
            <h3>2018 and before</h3>
            <p>
              <ul>
                <li><a href="https://theoutline.com/post/4904/the-online-support-groups-for-former-inmates-and-their-loved-ones" alt="" target="_blank" rel="noopener noreferrer">June 10, 2018 - The Outline: The Online Groups for Former Inmates and Their Loved Ones</a></li>
                <li><a href="https://www.congress.gov/congressional-report/115th-congress/senate-report/209/1?outputFormat=pdf" alt="" target="_blank" rel="noopener noreferrer">February 26, 2018 - Report of the Committe on Homeland Security and Governmental Affairs, United States Senate, to accompany S. 1281</a></li>
                <li><a href="https://digital.gov/2017/05/18/the-next-step-towards-a-bug-bounty-program-for-the-technology-transformation-service/" alt="" target="_blank" rel="noopener noreferrer">May 18, 2017 - Digital.gov: The Next Step Towards a Bug Bounty Program for the Technology Transformation Service</a></li>
                <li><a href="https://www.rfid-smart.com/blog/rfid-news/family-open-sources-entrepreneurs-rfid-solutions.html" alt="" target="_blank" rel="noopener noreferrer">March 23, 2017 - AsiaRFID: Family Open-Sources Entrepreneur's RFID Solutions</a></li>
                <li><a href="https://www.rfidjournal.com/family-open-sources-entrepreneurs-rfid-solutions" alt="" target="_blank" rel="noopener noreferrer">March 15, 2017 - RFID Journal: Family Open-Sources Entrepreneur’s RFID Solutions</a></li>
                <li><a href="https://www.gainesvilleregister.com/community/donations-help-support-state-school-football-program/article_21b86f00-5fd3-11e6-93bc-23dfbb0acb4f.html" alt="" target="_blank" rel="noopener noreferrer">August 11, 2016 - The Gainesville Register: Donations help support state school football program </a></li>
                <li><a href="https://www.texasstandard.org/stories/this-football-team-has-a-booster-club-of-ex-convicts/" alt="" target="_blank" rel="noopener noreferrer">August 10, 2016 - The Texas Standard: This Football Team Has A Booster Club of Ex-Convicts</a></li>
                <li><a href="http://the8percent.com/football-is-breaking-down-the-cycle-of-youth-crime/" alt="" target="_blank" rel="noopener noreferrer">August 5, 2016 - The 8 Percent: Football is breaking down the cycle of youth crime</a></li>
                <li><a href="https://www.dallasobserver.com/arts/ex-convicts-are-raising-thousands-of-dollars-for-a-football-team-in-north-texas-8536934" alt="" target="_blank" rel="noopener noreferrer">July 28, 2016 - Dallas Observer: Ex-Convicts Are Raising Thousands of Dollars for a Football Team in North Texas</a></li>
                <li><a href="https://www.youtube.com/watch?v=ZoHFGnGtCrQ" alt="" target="_blank" rel="noopener noreferrer">December 9, 2008 - Boca Raton City Council special election speech</a></li>
              </ul>
            </p>
          </main>
          
        </div>
      </div>
    </div>