<div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="/" alt="The home page and where I provide a little information about myself.">About Me</a></li>
                <li class="usa-sidenav__item"><a href="liverpool-fc.php" alt="A page that has a few quotes and things I like related to Liverpool FC.">Liverpool FC</a></li>
                <li class="usa-sidenav__item"><a href="make-mom-proud.php" alt="Media and other mentions of my work that made my mom proud of me.">Make Mom Proud</a></li>
              </ul>
            </nav>
          </div>
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Making My Mom Proud</h1>
            <p class="usa-intro">Articles, Interviews, and Media Mentions</p>
            <p>These are the things I've done to make sure my mom has something to brag about.</p>
            <p>
              <ul>
                <li><a href="https://www.actiac.org/events/emerging-technology-and-workforce-effecting-or-affected-question" alt="" target="_blank" rel="noopener noreferrer">May 20, 2020 - Emerging Technology and the Workforce: Effecting or Affected? That is the Question</a></li>
                <li><a href="https://www.actiac.org/events/act-iac-emerging-technology-coi-may-2020" alt="" target="_blank" rel="noopener noreferrer">May 19, 2020 - Emerging Technology Uses Cases in Acquisition</a></li>
                <li><a href="https://governmentciomedia.com/listen-gsa-centers-excellence-ai-leaders-omid-ghaffari-tabrizi-krista-kinnard" alt="" target="_blank" rel="noopener noreferrer">May 13, 2020 - GovernmentCIO GovCast Podcast: Season 3, Episode 15</a></li>
                <li><a href="https://digital.gov/2020/04/24/experimenting-with-micropurchase-threshold/" alt="" target="_blank" rel="noopener noreferrer">April 24, 2020 - Experimenting with the Micro-Purchase Threshold</a></li>
                <li><a href="https://digital.gov/event/2020/03/25/navigating-acquisition-procurement-for-artificial-intelligence/" alt="" target="_blank" rel="noopener noreferrer">March 25, 2020 - Navigating Acquisition and Procurement for Artificial Intelligence and Advanced Data Analytics</a></li>
                <li><a href="https://18f.gsa.gov/2020/03/18/an-acquisition-retrospective/" alt="" target="_blank" rel="noopener noreferrer">March 18, 2020 - An Acquisition Retrospective</a></li>
                <li><a href="https://nova.afceachapters.org/event/2nd-annual-intelligence-community-it-day" alt="" target="_blank" rel="noopener noreferrer">February 19, 2020 - AFCEA NOVA 2nd Annual Intelligence Community IT Day</a></li>
                <li><a href="https://www.linkedin.com/feed/update/urn:li:activity:6623302338050351104/" alt="" target="_blank" rel="noopener noreferrer">January 15, 2020 - DITAP training on Acqusition Innovation</a></li>
                <li><a href="https://governmentciomedia.com/gsa-explored-emerging-technologies-and-acquisition-innovation-2019" alt="" target="_blank" rel="noopener noreferrer">January 2, 2020 - GSA Explored Emerging Technologies and Acquisition Innovation in 2019 </a></li>
                <li><a href="https://www.federaltimes.com/it-networks/2019/12/06/how-the-pentagons-ai-team-can-benefit-civilian-agencies/" alt="" target="_blank" rel="noopener noreferrer">December 6, 2019 - How the Pentagon’s AI team can benefit civilian agencies</a></li>
                <li><a href="https://governmentciomedia.com/cxo-tech-forum-ai-2019" alt="" target="_blank" rel="noopener noreferrer">December 5, 2019 - GovernmentCIO CXO Tech Forum: AI and RPA in Government</a></li>
                <li><a href="https://fcw.com/articles/2019/10/31/rising-stars/rs_ghaffari.aspx" alt="" target="_blank" rel="noopener noreferrer">October 31, 2019 - FCW Government Innovation Rising Star Profile</a></li>
                <li><a href="https://fcw.com/articles/2019/08/26/rising-stars-2019.aspx" alt="" target="_blank" rel="noopener noreferrer">August 26, 2019 - FCW Government Innovation Rising Star Award</a></li>
                <li><a href="https://governmentciomedia.com/GSA-Centers-of-Excellence-Spur-Procurement-Innovation" alt="" target="_blank" rel="noopener noreferrer">June 25, 2019 - GSA's Centers of Excellence Spur Procurement Innovation</a></li>
                <li><a href="https://www.eventbrite.com/e/cxo-tech-forum-acquisition-innovation-tickets-54314881272?aff=efbneb#" alt="" target="_blank" rel="noopener noreferrer">June 20, 2019 - GovernmentCIO CXO Tech Forum: Acquisition Innovation</a></li>
                <li><a href="https://twitter.com/GSACoE/status/1141489654899888128" alt="" target="_blank" rel="noopener noreferrer">June 19, 2019 - NCMA DC Monthly Meeting</a></li>
                <li><a href="https://twitter.com/GSACoE/status/1126217478856687616" alt="" target="_blank" rel="noopener noreferrer">May 8, 2019 - Tweet for CoE</a></li>
                <li><a href="https://theoutline.com/post/4904/the-online-support-groups-for-former-inmates-and-their-loved-ones?zd=1&zi=hsb2waeg" alt="" target="_blank" rel="noopener noreferrer">June 10, 2018 - The Online Groups for Former Inmates and Their Loved Ones</a></li>
                <li><a href="https://www.congress.gov/congressional-report/115th-congress/senate-report/209/" alt="" target="_blank" rel="noopener noreferrer">February 26, 2018 - Report of the Committe on Homeland Security and Governmental Affairs, United States Senate, to accompany S. 1281</a></li>
                <li><a href="https://digital.gov/2017/05/18/the-next-step-towards-a-bug-bounty-program-for-the-technology-transformation-service/" alt="" target="_blank" rel="noopener noreferrer">May 18, 2017 - The Next Step Towards a Bug Bounty Program for the Technology Transformation Service</a></li>
                <li><a href="https://www.texasstandard.org/stories/this-football-team-has-a-booster-club-of-ex-convicts/" alt="" target="_blank" rel="noopener noreferrer">August 10, 2016 - This Football Team Has A Booster Club of Ex-Convicts</a></li>
                <li><a href="https://www.dallasobserver.com/arts/ex-convicts-are-raising-thousands-of-dollars-for-a-football-team-in-north-texas-8536934" alt="" target="_blank" rel="noopener noreferrer">July 28, 2016 - Ex-Convicts Are Raising Thousands of Dollars for a Football Team in North Texas</a></li>
                <li><a href="https://www.youtube.com/watch?v=ZoHFGnGtCrQ" alt="" target="_blank" rel="noopener noreferrer">December 9, 2008 - Boca Raton City Council special election speech</a></li>
              </ul>
            </p>
          </main>
        </div>
      </div>
    </div>